### ISSUE TITLE
Implement MVC model

### ISSUE THREAD

**Issue by mariobehling** [fossasia/engelsystem#163]
Due to the process the application was developed there is no clear MVC model. 
- [x] Please propose a way to change all components and code structure to a clean Model View Controller model (MVC). 
- [x] Create a list of issues here (in this parent issue) and link them.
- [x] Get other contributors around you to take on issues
- [x] Document all changes in a blog post.

**Comment by hongquan** [comment]
Current condition:
- The code base seems to be structured in MVC. There are folders: _model_, _view_, _controller_, _pages_.
- Code in _pages_ seems to be a mix of model and controller. By reading _public/index.php_, you can see that functions in _pages_ act as controller. But it has SQL queries inside, which should be placed in model.

So I think what we have to do is to redo the _pages_ code.

**Comment by vuhung** [comment]
MVC is a standard 3-tier architecture. 
By adding a new tier "page", I think there must be some intention for doing that. We should ask the creator before making change to the architecture.

**Comment by mariobehling** [comment]
@vuhung The origin of Engelsystem is long ago and @msquare has already started to implement MVC. So, he would be happy if this is implemented as it would make life easier for everyone.

@kamishettysreeja25 Please outline your ideas and what you plan to do before you start.

**Comment by sreejakshetty** [comment]
@mariobehling  I will propose a plan and outline a way to change all components and code structure to a clean Model View Controller model by today.

**Comment by sreejakshetty** [comment]
Presently there are 26 pages. we need to create controller files for all of them. For the pages which access SQL query we need to separate them into model files. There are only model files for a few pages. We should also add view to render the html or forms for some of the pages.
**Pages**

```
admin_active.php
admin_arrive.php
admin_export.php
admin_free.php
admin_groups.php
admin_import.php
admin_log.php
admin_news.php
admin_questions.php
admin_rooms.php
admin_settings.php
admin_shifts.php
admin_user.php
guest_credits.php
guest_login.php
guest_start.php
guest_stats.php
user_atom.php
user_ical.php
user_messages.php
user_myshifts.php
user_news.php
user_questions.php
user_settings.php
user_shifts.php
```

**Model**

```
AngelType_model.php
LogEntries_model.php
Message_model.php
NeededAngelTypes_model.php
Room_model.php
Settings_model.php
ShiftEntry_model.php
ShiftTypes_model.php
Shifts_model.php
UserAngelTypes_model.php
UserDriverLicenses.model.php
User_model.php

```

**Controller**

```
angeltype_controller.php
rooms_controller.php
shifts_controller.php
shifttypes_controller.php
user_angeltypes_controller.php
user_driver_licenses_controller.php
user_controller.php
```

**view**

```
AngelTypes_view.php
Questions_view.php
Rooms_view.php
ShiftEntry_view.php
ShiftTypes_view.php
Shifts_view.php
UserAngelTypes_view.php
UserDriverLicenses_view.php
User_view.php


```

For Example, We are having `admin_shifts.php` which access both the`shifts model` and `controller file.`We need to move the content to controller and create a view file for admin_shifts.

**Comment by vuhung** [comment]
A big refactoring! Great summary!

**Comment by sreejakshetty** [comment]
This is a big issue. I will create smaller issues. There are 26 pages. I would like to even reduce the NP complexity by re factoring the code into smaller functions. Each  will consists of modifying 3 pages and making them MVC structured.

**Comment by sreejakshetty** [comment]
Deleted all the admin pages and created admin controller pages. Updates install.sql, update.sql, engelsystem_provider.php, sys_menu.php.
https://github.com/fossasia/engelsystem/issues/168
https://github.com/fossasia/engelsystem/issues/169
https://github.com/fossasia/engelsystem/issues/170
https://github.com/fossasia/engelsystem/issues/171
https://github.com/fossasia/engelsystem/issues/172
Commits: https://github.com/fossasia/engelsystem/commit/a2b3d067446f8b2e363c5b35d7a3b5d24f3d62d3

**Comment by mariobehling** [comment]
Where is the pull request? Who reviewed this?

**Comment by sreejakshetty** [comment]
@mariobehling This issue is completed. Now code structure is in  MVC model. 
There are sys files like template, auth, log, menu, page. These files can also be moved to controller, model, view folder. Should I move them and remove includes folder or should I leave it in the same structure.

**Comment by sreejakshetty** [comment]
@mariobehling  
This issue is completed. Implemented a MVC model for all the pages. We can close this.

**Comment by mariobehling** [comment]
Great! Good job both of you!
