### ISSUE TITLE
Implement MVC for user news, questions, settings and shifts pages

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#175]
Parent Issue #163 
- [x] user_news.php
- [x] user_questions.php
- [x] user_settings.php
- [x]  user_shifts.php

Create controller and view files .

**Comment by DishantK1807** [comment]
Fixed here #187

**Comment by sreejakshetty** [comment]
Fixed here #192
