### ISSUE TITLE
Writing test for Travis-CI 

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#191]
We need to set up Travis to run tests for our system. We need to write test codes for model and view, that  Travis will run, and script that will allow travis to set up database and run other commands for tests
- [x] Writing test for model files
- [x] Writing script to set-up database and run tests
- [x] Updating the `.travis.yml` file

**Comment by vuhung** [comment]
> Writing script to set-up database and run tests

What kind of script do you plan to write?
I thought it is some kind of database migration scirpts.

**Comment by sreejakshetty** [comment]
> What kind of script do you plan to write?
> I thought it is some kind of database migration scirpts.

@vuhung All the installation instructions can be written in bash script.

**Comment by DishantK1807** [comment]
https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Installation-Step

@kamishettysreeja25: Have you completed the script for the Travis?

**Comment by sreejakshetty** [comment]
@DishantK1807 I have written the script for both environment setup and database setup.  `The script you provide to TravisCI should only do setup database job.`
You can see the script file here https://github.com/kamishettysreeja25/engelsystem/blob/9cd643fd16567eb883cdb9d9dbb2fa6f40d92688/install.sh.

**Comment by DishantK1807** [comment]
https://github.com/travis-ci-examples/php/blob/master/.travis.yml

Example .travis.yml

**Comment by DishantK1807** [comment]
@kamishettysreeja25: What about Migration of database?

**Comment by sreejakshetty** [comment]
@DishantK1807 I have setup the table and migrated the tables in install.sh file.

**Comment by DishantK1807** [comment]
@hongquan: Can we setup database as shown in this example?
https://github.com/travis-ci-examples/php/blob/master/.travis.yml

**Comment by hongquan** [comment]
@DishantK1807 Can. But note that that example is not enough. It doesn't setup the tables.

**Comment by DishantK1807** [comment]
@hongquan: Can we setup tables in the same way? 

I'll research more.

**Comment by hongquan** [comment]
@DishantK1807 Of course yes, if there is no limitation of travis.yml which blocks it. I only worry that travis.yml has some limitations which stop you doing so.

**Comment by DishantK1807** [comment]
https://docs.travis-ci.com/user/database-setup/

Will try setting-up the the database via .travis.yml . Thank you
